<div class="errorPage">

		<div align="center">
			<h1><b>204</b></h1>
			<h1>Invalid Controller</h1>
			<p>The requested <span style="padding: 5px; background: #fcfcfc; color: #f20;"><?=$this->boot['active_c'].'/'?></span> has no contents and cannot be rendered. Please see sitemap below for avaliable Controllers.</p>
			<ul>
				<?php
					$controllers = $this->boot['controllers'];
					foreach($controllers as $key => $controller)
					{
						if(!empty($controller))
						{
							$controller = trim($controller);
							echo '<li><a href="'.$url($controller).'">'.ucwords($controller).'</a></li>';
						}
					}
				?>
			</ul>
		</div>

</div>	